platform :ios, '11.0'
use_frameworks!

target "WebRTCDemo" do
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'CommonCryptoModule'
  pod 'AWSKinesisVideo'
  pod 'AWSKinesisVideoSignaling'
  pod 'GoogleWebRTC'
  pod 'Starscream', '~> 3.0'
end

target "WebRTCDemoBroadcast" do
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'CommonCryptoModule'
  pod 'AWSKinesisVideo'
  pod 'AWSKinesisVideoSignaling'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'Starscream', '~> 3.0'
end

target "WebRTCDemoSignalling" do
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'CommonCryptoModule'
  pod 'AWSKinesisVideo'
  pod 'AWSKinesisVideoSignaling'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'Starscream', '~> 3.0'
end


target "AwsSignalling" do
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'CommonCryptoModule'
  pod 'AWSKinesisVideo'
  pod 'AWSKinesisVideoSignaling'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'Starscream', '~> 3.0'
end
